
= issue 20220815

== Land planes

* assignee : Nicholas Prado
* status : in progress
* priority : medium

Ensure that Haokkoz can land planes at their respective airports.

== comments

=== 2022-09-19

The effort to treat points within a distance to a particular map node should expense to this issue, rather than i20220823.

Is this fast enough to ask for all the map node points ?
Should I just put everything in a priority queue and weight based on whether an airplane is there or has a flight path in that direction ?
What a pain that didn't need to be put on the client.

.  uses/hao/ParcelMap
.  app/service/MapsNodePixels
.  saving new map creates a 'parcel map' message
.  queue from MapCache to MapsNodePixels (or is it to map service ?)

=== 2023-11-09

comment author : Nicholas Prado

Airplanes now store their accepted and proposed plan.
The distinction stems from the idea that the game might reject the proposed plan, so any routing should only account for the accepted plan.

At this moment, AirplaneDispatch prepares a simple plan that moves directly away from the nearest wall in a cardinal direction.
(I would like to avoid moving planes diagonally, though it is valid, to avoid complicating my routing by requiring different flight speeds.)

At this time, I plan to only generate a new flight plan when the airplane is close to its final node.
That way, I don't need to worry about routing around the accepted and proposed plan.

I am inclined to simplify the routing simulation by generating a distance map for each airport.
They aren't changing, so the routing algorithm can try to move closer or, at least, not farther from the destination.


////
== comments
=== yyyy-MM-dd hh:MM zzz

=== --

comment author : 

comment_here
////




















